#Obter csv das médias de todos os dias
SELECT DAY, TIME, API, PLATFORM, LANGUAGE, ACTIVITY, FILESIZE, AVG(LATENCY), AVG(MEMORY), AVG(CPUTIME)
FROM OBSERVATION
GROUP BY DAY, API, PLATFORM, LANGUAGE, ACTIVITY, FILESIZE
ORDER BY DAY ASC, TIME ASC, FILESIZE ASC
INTO OUTFILE '/tmp/query.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';

#Obter csv de todas amostras
SELECT DAY, TIME, API, PLATFORM, LANGUAGE, ACTIVITY, FILESIZE, LATENCY, MEMORY, CPUTIME
FROM OBSERVATION
INTO OUTFILE '/tmp/queryFULL.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';

#Obter médias de todos os dias
SELECT DAY, COUNT(*), MIN(TIME), MAX(TIME), API, PLATFORM, LANGUAGE, ACTIVITY, FILESIZE, AVG(LATENCY), AVG(MEMORY), AVG(CPUTIME)
FROM OBSERVATION
GROUP BY DAY, API, PLATFORM, LANGUAGE, ACTIVITY, FILESIZE
ORDER BY DAY ASC, TIME ASC, FILESIZE ASC;

#Obter todas as amostras
SELECT *
FROM OBSERVATION
WHERE DAY="2016-04-07" AND API="multicloud" AND PLATFORM="aws" AND LANGUAGE="python" AND ACTIVITY="upload" AND FILESIZE=310
ORDER BY DAY ASC, TIME ASC, FILESIZE ASC;

#Obter Médias de um dia
SELECT DAY, MIN(TIME), MAX(TIME), API, PLATFORM, LANGUAGE, ACTIVITY, FILESIZE, AVG(LATENCY), AVG(MEMORY), AVG(CPUTIME)
FROM OBSERVATION
WHERE DAY="2016-04-07"
GROUP BY DAY, API, PLATFORM, LANGUAGE, ACTIVITY, FILESIZE
ORDER BY DAY ASC, TIME ASC, FILESIZE ASC;